/*********************************************************************/
/*            Start up JFC WEBBLOCKER                                */
/*                                                                   */
/*  CMD JFCBLOCKER                                                   */
/*********************************************************************/
             cmd

             PARM       KWD(FILE) TYPE(*CHAR) LEN(10) +
                          CONSTANT('WEBBLOCKER')

             PARM       KWD(SITE) TYPE(*CHAR) LEN(10) +
                          CONSTANT('RDW       ')
