/*********************************************************************/
/*            Start up JFC WEBVISITOR                                */
/*                                                                   */
/*  CMD JFCVISITOR                                                   */
/*********************************************************************/
             cmd

             PARM       KWD(FILE) TYPE(*CHAR) LEN(10) +
                          CONSTANT('WEBVISITOR')

             PARM       KWD(SITE) TYPE(*CHAR) LEN(10) +
                          CONSTANT('RDW       ')
